### ISSUE TITLE
Grant access to Heroku apps to Dave M & CR Admin

### ISSUE THREAD

**Issue by dmiyamasu** [crdschurch/worship-training#3]
Please grant access to these two users in Heroku:
- dmiyamasu@crossroads.net
- cradmin@crossroads.net

to these Heroku apps:
1) https://dashboard.heroku.com/apps/floating-gorge-63136/logs (production) 
2) https://dashboard.heroku.com/apps/enigmatic-peak-55319/logs (staging)

**Comment by lukemoderwell** [comment]
@dmiyamasu added 👍
